#!/bin/bash

set -x

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
### Define NET/RUN variables
######################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-seasonal}
export RUN=${RUN:-atmos}
export machine=${machine:-WCOSS2}

################################################################
# Set data directives
# SENDCOM=YES--Copy files from TMPDIR to $COMOUT
# SENDMAIL=YES--Send missing data emails
# SENDECF=YES--Flag events on ecflow
# SENDDBN=YES--Issue DBNet client calls
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDMAIL=${SENDMAIL:-NO}
export SENDDBN=${SENDDBN:-YES}       # need to set to NO for testing
export SENDECF=${SENDECF:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

################################################################
# Set EVS directories
################################################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-$HOMEevs/fix}

export cfs_members="4"

################################################################
# Run setpdy and initialize PDY variables
################################################################
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh
. ./PDY

export INITDATE=$PDYm2

#################################################
# Set up the INPUT and OUTPUT directories
#################################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/$NET/$evs_ver)}
export COMINcfs=${COMINcfs:-$(compath.py ${envir}/com/cfs/${cfs_ver}/cfs.$INITDATE)}
export DCOMINghrsst=${DCOMINghrsst:-$DCOMROOT}
#export COMINgfs=${COMINgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})}
#export DCOMINecmwf=${DCOMINecmwf:-$DCOMROOT}
#export DCOMINosi=${DCOMINosi:-$DCOMROOT}
#export DCOMINghrsst=${DCOMINghrsst:-$DCOMROOT}
#export DCOMINumd=${DCOMINumd:-$DCOMROOT}
#export COMINobsproc=${COMINobsproc:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}
#export COMINccpa=${COMINccpa:-$(compath.py ${envir}/com/ccpa/${ccpa_ver})}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}

#######################################################################
# Execute the script
#######################################################################
env
$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${PREP_TYPE}_${STEP}.sh
export err=$?; err_chk


if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
